longform_info_text = "This functionality allows you to generate longform content. Select a topic; imagine it is the title of a book, novel or podcast.\n\nTo continue, simply reply to this message with the title."


LangMap = {
    "af": "af-ZA",
    "ar": "ar-XA",
    "bn": "bn-IN",
    "bs": "bs-BA",
    "bg": "bg-BG",
    "ca": "ca-ES",
    "zh": "zh-CN",  # This is for Simplified Chinese; for Traditional Chinese, use "zh-TW"
    "hr": "hr-HR",
    "cs": "cs-CZ",
    "da": "da-DK",
    "nl": "nl-NL",
    "en": "en-US",
    "et": "et-EE",
    "tl": "fil-PH",
    "fi": "fi-FI",
    "fr": "fr-FR",
    "de": "de-DE",
    "el": "el-GR",
    "gu": "gu-IN",
    "iw": "he-IL",
    "hi": "hi-IN",
    "hu": "hu-HU",
    "is": "is-IS",
    "id": "id-ID",
    "it": "it-IT",
    "ja": "ja-JP",
    "kn": "kn-IN",
    "ko": "ko-KR",
    "lv": "lv-LV",
    "lt": "lt-LT",
    "mk": "mk-MK",
    "ms": "ms-MY",
    "mt": "mt-MT",
    "no": "nb-NO",
    "fa": "fa-IR",
    "pl": "pl-PL",
    "pt": "pt-PT",
    "pa": "pa-IN",
    "ro": "ro-RO",
    "ru": "ru-RU",
    "sr": "sr-RS",
    "sk": "sk-SK",
    "sl": "sl-SI",
    "es": "es-ES",
    "sw": "sw-TZ",
    "sv": "sv-SE",
    "ta": "ta-IN",
    "te": "te-IN",
    "th": "th-TH",
    "tr": "tr-TR",
    "uk": "uk-UA",
    "ur": "ur-PK",
    "vi": "vi-VN",
}
